# fly.toml app configuration file generated for chat-context-api on 2023-09-24T21:56:06-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "chat-context-api"
primary_region = "scl"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
